package try_catch_ex;

import java.lang.reflect.Array;

public class MainTest1 {
	
	public void print(String string) {
        String print2 = string;
        System.out.println(print2);
	}
	
	public static void main(String[] args) {
	
		Exception exception;
		
	        try {
	         
	        } catch (NullPointerException e) {
	            System.out.println("예외 발생");
	  
	    }

		
	}
}
